sudo: required
services:
  - docker

before_install:
  - docker build -t jascks/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jascks/react-test npm test -- --coverage

after_success:
  - docker build -t jascks/udemy-multi-client ./client
  - docker build -t jascks/udemy-multi-nginx ./nginx
  - docker build -t jascks/udemy-multi-server ./server
  - docker build -t jascks/udemy-multi-worker ./worker

# Push images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jascks/udemy-multi-client
  - docker push jascks/udemy-multi-nginx
  - docker push jascks/udemy-multi-server
  - docker push jascks/udemy-multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "jschmidt-udemy-multi-docker"
  env: "JschmidtUdemyMultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-705370621539"
  bucket_path: "jschmidt-udemy-multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY" 